### ISSUE TITLE
move to guzzle 6

### ISSUE THREAD

**Issue by aoberoi** [opentok/OpenTok-PHP-SDK#132]
guzzle 3 is deprecated.

**Comment by aoberoi** [comment]
guzzlehttp/guzzle

**Comment by Gadgetdude** [comment]
Guzzle 6 has been released as well. Maybe this issue should also be marked as "security".

**Comment by aoberoi** [comment]
thanks @Gadgetdude, title updated. Guzzle 6 and PSR-7 look like a great advancement. and yes, since guzzle 4 is EOL, this would be a security concern. i like the idea for that label :)

**Comment by zedee** [comment]
Is there any estimation about when this dependency will be upgraded?

**Comment by aoberoi** [comment]
i was hoping to take a crack at this issue today but then i noticed that any upgrades would mean introducing some breaking changes.

even incrementing one major version (to guzzle 4) would mean dropping support for PHP 5.3. but noting that guzzle 4 is no longer supported and that the php version constraint is the exact same for guzzle 5, that is the least we should update to. moving to guzzle 6 would require leapfrogging to a minimum requirement of PHP 5.5.

i'd love to move straight to guzzle 6, but before we make any moves, i think its important to evaluate what impact this will have on the users of the library. i don't want to be in the business of maintaining a legacy branch for those who could not upgrade.

so clearly, we need data. [general data about the PHP community](https://w3techs.com/technologies/details/pl-php/5/all) isn't giving me any hope of updating at all:
<img width="394" alt="screen shot 2016-08-27 at 7 33 05 pm" src="https://cloud.githubusercontent.com/assets/494795/18031274/2a3e0312-6c8d-11e6-9c86-323f25052dcb.png">

i'm hoping that at tokbox we can do some more specific analysis of the users of this library and abandon either PHP 5.3 or both 5.3 and 5.4.

**Comment by aoberoi** [comment]
@agnesnanxin i need your help to find the relevant data for this issue. would you be able to enhance the user-agent parser in your ETL job so that specifically when we have a string that matches the PHP SDK, we not only extract the version of the SDK, but also the version of PHP? you can find this in the string by looking for a token that looks like " PHP/{PHP_VERSION}" (notice the preceding space).

**Comment by Gadgetdude** [comment]
@aoberoi I've seen many discussions about which PHP versions to support before in open source projects. It is always nice to have a broad range of supported versions, but that doesn't mean older versions of an open source project aren't available anymore and will break when they're not updated for a long time anymore. Guzzle 3 has been unsupported for over a year now, just like PHP 5.3 and 5.4. So I would argue that dropping maintenance of the current major version and work with only non-EOL packages isn't that bad of an option. It would decrease the security risks concerning older unsupported versions and give users an option to migrate to the new version.

In case of an SDK it might be a little bit more tricky to just suddenly stop maintaining a certain version, maybe doing only (hot)fixes on that branch only might be an option. New functionality should then only be added to the Guzzle 6 branch.

There are also other project that maintain a backwards compatibility layer for certain PHP versions, but it's hard to maintain and I'm not sure how you would be able to solve it in composer. Using the suggests tag for both Guzzle versions is an option. You would be able to check if the new classes are available and use them, but it's also not very maintainable since you can't have a version constraint for a composer suggestion.

**Comment by Hypnopompia** [comment]
Composer is now throwing warnings about this.

`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`

**Comment by freefri** [comment]
People can keep using the old versions of opentok, if they are not upgrading their opentok system they won't mind to loose compatibility with php5.3 or php5.4
If they want to upgrade opentok library, they should also think to upgrade to php, even php5.5 is [no longer supported](http://php.net/supported-versions.php)

**Comment by aiham** [comment]
@freefri @Hypnopompia @Gadgetdude @zedee I'm working on this now.

**Comment by aiham** [comment]
I've just released v3.0.0 which has a minimum PHP version of 5.6 and supports PHP 7+, so we no longer have any issues with version compatibility, but I've looked at [migration from guzzle 3 to guzzlehttp 4](https://github.com/guzzle/guzzle/blob/master/UPGRADING.md#3x-to-40) and I just don't have the capacity right now to make those changes. I'm happy to accept a reasonable PR if anyone is up for it. Thanks

**Comment by jamesgraham** [comment]
Thanks for the update @aiham. Forgive my ignorance but why would you not want a rewrite directly to Guzzle 6, instead of another EOL version?

![image](https://user-images.githubusercontent.com/934542/27725521-5f0b2d84-5d7f-11e7-82b0-91d6c7546bed.png)

**Comment by torchello** [comment]
Guys, what's latest status with Guzzle upgrade? This becomes a blocker for an upgrade to Symfony 3.x as Guzzle 3.7 depends on Symfony Event Dispatcher 2.1 and this results in a conflict.

**Comment by ArondeParon** [comment]
Would love a status update as well.

**Comment by cmdearcos** [comment]
Me too

**Comment by putnik** [comment]
I started to rewrite using Guzzle 6. There's a lot of work there, almost everything that affects the requests will have to be changed. Given the time for vacation and more urgent tasks, I expect to finish by early February.

**Comment by aiham** [comment]
@Gadgetdude @zedee @Hypnopompia @freefri @jamesgraham @torchello @ArondeParon @cmdearcos @putnik 

[v4.0.0-alpha.1](https://github.com/opentok/OpenTok-PHP-SDK/releases/tag/v4.0.0-alpha.1) has been released with Guzzle 6. If anyone is able to I'd appreciate if you could test it and let me know of any problems you find.

I'll close this ticket once v4.0.0 has been released.

Thanks

**Comment by aiham** [comment]
https://github.com/opentok/OpenTok-PHP-SDK/releases/tag/v4.0.0

**Comment by siddheshkerkar** [comment]
Thanks for the update.

I have upgraded to Tokbox to 4.0.0 and Guzzle 6. But while creating session using **createSession** method on my local system I am getting exception as **"SSL certificate problem: self signed certificate in certificate chain"**. Its working fine on production due to enabled SSL. Anybody else is facing this issue ?

I debugged for the same and found Guzzle 6 uses verify SSL flag as True by default and hence connection to Tokbox api is failing on localhost.

@aiham Can you please suggest on this?
