### ISSUE TITLE
getting error on hello world, please help

### ISSUE THREAD

**Issue by thetechie13** [opentok/OpenTok-PHP-SDK#140]
<img width="1005" alt="screen shot 2015-09-23 at 4 29 01 pm" src="https://cloud.githubusercontent.com/assets/4559844/10043386/52951ef0-6210-11e5-94f5-2857b8345301.png">

**Comment by aoberoi** [comment]
@thetechie13 it looks like you are using this sample app: https://github.com/opentok/opentok-ios-sdk-samples/tree/develop/1.Hello-World

the application uses Cocoapods to manage dependencies. first, go ahead and install Cocoapods using the instructions here: https://cocoapods.org/. then, inside the project directory run `pod install` on the command line. finally, open the Hello-World.xcworkspace file in Xcode (*not* Hello-World.xcodeproj).

if you need more help with this sample, please see support.tokbox.com or create an issue in the above repository so that its within the context of that sample.
