### ISSUE TITLE
Defining API and API-SECRET.

### ISSUE THREAD

**Issue by Ragnorok-Gs** [opentok/OpenTok-PHP-SDK#191]
Everything went smoothly after executing [run-demo], but the server is showing again and again to " define an API_KEY and API_SECRET in the run-demo file", which i have done. 

I got **API** and **SECRET** key from my Tok-account but still i'm getting this error.

Here is copy of my exact run-demo.bat
```
#!/bin/sh



if [ -z "$API_KEY" ] || [ -z "$API_SECRET" ]

then
  
	export API_KEY=xxxxxxxx
	export API_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxx
fi


if [ -d "cache" ]

then
  
	rm -rf cache/

fi



php -S localhost:8080 -t web web/index.php

```

xxxx replaced with my API and SECRET, please i need help!!

**_Thanks 
Gautham Sevar_**

**Comment by aiham** [comment]
Hi,

Looks like you have shell code in your `.bat` file. Are you sure you got the right code for your operating system? Are you using windows or mac/linux?

Can you also close your terminal completely and try again with a brand new terminal window? An older key/secret is probably still in your shell and isn't getting overwritten because of the conditional in the script.

We should probably fix these scripts to be a bit more robust, preferably getting rid of the environment variables and just pulling credentials out of a JSON file.

**Comment by Ragnorok-Gs** [comment]
I'm using Windows7_x64_SP1 and i did close the terminal and executed the script "run-demo" in new terminal. 
But still the "You must define an API_KEY and API_SECRET in the run-demo file" is getting displayed.

**Comment by Ragnorok-Gs** [comment]
I solved it.

I just included the [KEYS] in run-demo file and leaving the run-demo.bat blank, then after editing the .bat file it worked fine.

Thank you aiham

**Comment by aiham** [comment]
That's good to hear.

Running the samples apps should be simpler in the future, with less moving parts that can complicate the process.

**Comment by Im10Anish** [comment]
I have added API_KEY and API_SECRET in both run-demo and run-demo.bat files but it still shows the same error. I am using Window 7 by the way
