### ISSUE TITLE
ListStreams() Error

### ISSUE THREAD

**Issue by jsandfordhughes** [opentok/OpenTok-PHP-SDK#267]
When calling the listStreams() method I get a 

`OpenTok\Exception\DomainException
The OpenTok API request failed: Session not found`

This happens when no one is connected to the session, after a client is connected to the session, either publishing or subscribing then the method returns correctly. Is this a bug with the OpenTok servers?

**Comment by dragonmantank** [comment]
This is actually the intended response from the API itself. Until a connection has been added to a session, it doesn't really exist so hasn't been created. The raw API will behave the same way by returning a 404.

We're working on making this [more clear in the SDK so that it is easier to handle](https://github.com/opentok/Opentok-.NET-SDK/issues/127).

**Comment by jsandfordhughes** [comment]
Okay thank you
