### ISSUE TITLE
Client error: `POST https://api.opentok.com/session/create` resulted in a `403 Forbidden` response: <?xml version="1.0" encoding="UTF-8" standalone="yes"?><errorPayload><code>-1</code><message>No suitable authentication (truncated...) in my larvel project

### ISSUE THREAD

**Issue by yogeshebslon** [opentok/OpenTok-PHP-SDK#284]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Operating System and version:

**Comment by yogeshebslon** [comment]
please help me

**Comment by dragonmantank** [comment]
Hello! Could you please edit the initial issue with information so that we could help troubleshoot? From the looks of the error you're possibly not supplying the correct credentials, but the exact code you are using to create the client and call it would be helpful. Please also let us know what version of PHP and the OpenTok library you are using so we can see if there are any issues there.

Thanks!
