### ISSUE TITLE
Error 409  with  the "startArchive" function

### ISSUE THREAD

**Issue by anaselatiq** [opentok/OpenTok-PHP-SDK#326]
Hello, I am working on a Symfony 4 project and I have this error 409 when I integrate the following startarchive function, i m using the php sdk , can you help me pls??
here is my code and the error displayed:
![errorStartArchive](https://user-images.githubusercontent.com/6963825/216345968-b7d9b6a6-66d8-426f-ab0d-55fcb1fe1598.png)
![codeOpenTokService](https://user-images.githubusercontent.com/6963825/216345974-0a749ed7-58fd-47cd-ab48-e70a5b9b94d1.png)

**Comment by SecondeJK** [comment]
Hi, this is an error coming back from the API rather than the SDK. For more context, here is the reference page regarding starting an archive:

`The HTTP response has a 409 status code if you attempt to start an archive for a session that does not use the OpenTok Media Router. Or if you attempt to start an archive for a session that is already being recorded without setting the multiArchiveTag option. Or if you attempt to start a simultaneous archive for a session without setting a unique multiArchiveTag value.`

This is from this page:
https://tokbox.com/developer/rest/#start_archive
