### ISSUE TITLE
Get Archive by sessionId

### ISSUE THREAD

**Issue by aoberoi** [opentok/OpenTok-PHP-SDK#44]
It exists in the REST API. Does anyone have need for it in the SDK?

**Comment by aoberoi** [comment]
The REST API for querying archives is currently private.

**Comment by arif-medialinker** [comment]
how can we get archive list, as my code $archiveList = $opentok->listArchives(); return me empty veriable
why?

**Comment by pthreat** [comment]
@aoberoi I need it in order not to go over hundreds or thousand of sessions just to get archives from the session I'm looking for. Also, I couldn't just easily extend to OpenTok\OpenTok in order to reutilize the client since the client is a private property and has no getter. I'm using 2.5.x, please add this. 

Also note my report on https://stackoverflow.com/questions/44768499/opentok-jwt-authenticacion-bug

**Comment by msach22** [comment]
Released with 4.2.0
